language: node_js
node_js: stable

branches:
  only:
  - master

cache:
  directories:
    - node_modules
    - themes

before_install:
- openssl aes-256-cbc -K $encrypted_a9a057ac7852_key -iv $encrypted_a9a057ac7852_iv
  -in .travis/travis.key.enc -out ~/.ssh/id_rsa -d
- chmod 600 ~/.ssh/id_rsa
- git config --global user.name "Andy Deng"
- git config --global user.email "theandy.deng@gmail.com"

install:
- npm i -g hexo-cli
- npm i

script:
- npm run build
- hexo d

addons:
  ssh_known_hosts:
    - github.com
