title: Memory-copy
author: Andy Deng

url: https://andytimes.xyz
root: /
permalink: blog/:year/:month/:day/:title/

new_post_name: :year-:month-:day-:title.md # File name of new posts
render_drafts: false

highlight:
  enable: false
  backtick_code_block: true
  line_number: true
  tab_replace: "  "
  auto_detect: false

skip_render:
  - demo/**/*
  - lab/**/*
  - themes/**/*

include:
  - _headers

archive: 1
category: 1
tag: 1

archive_generator:
  per_page: 0

per_page: 5
pagination_dir: page
post_asset_folder: true

date_format: MMM D, YYYY

disqus_shortname:
google_analytics:

theme: tlwd

markdown:
  render:
    html: true

pretty_urls:
  trailing_index: false

deploy:
  type: git
  repo:
      github: git@github.com:andytimes/blog.git
      coding: git@git.coding.net:andytime/blog.git
  branch:
      github: gh-pages
      coding: master
  message: Update site to latest

