name: blog deploy

on:
  push:
    branches: [ master ]

jobs:
  build-and-deploy:
    run-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: set up node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: npm install
        run: |
          npm i -g hexo-cli
          npm i

      - name: env
        env:
          DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}
        run: |
          mkdir -p ~/.ssh
          echo "$DEPLOY_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan github.com >> ~/.ssh/known_hosts
          git config --global user.email "theandy.deng@gmail.com"
          git config --global user.name "Andy Deng"

      - name: run build
        run: |
          npm run build
          hexo d

